jodconverter:
#  local:
#    enabled: true
#    office-home: "H:/LibreOffice"
#    port-numbers: 8100,8101,8102
#    max-tasks-per-process: 10000
  online:
    enabled: true
    url: "http://192.168.0.118:9980/"
#     临时文件的存放目录
    working-dir: "F:/IdeaProjects/libre-office/src/main/resources/temp"
    pool-size: 50
    task-execution-timeout: 600000
    task-queue-timeout: 600000
  store:
    path: "F:/IdeaProjects/libre-office/src/main/resources/local"
spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      enabled: true
  freemarker:
    suffix: .html
  resources:
    static-locations: classpath:/templates/,classpath:/static/